# Student Perfoemance Dataset Cleaning and Manipulation

In [29]:
# Import necessary libraries
import pandas as pd

# Load the dataset
data = pd.read_csv("StudentsPerformance.csv")

# Display the first few rows to understand the data
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

### Explorig Dataset

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [31]:
data.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [32]:
# Count occurrences of each gender category
data['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [33]:
# Count occurrences of each race/ethnicity category
data['race/ethnicity'].value_counts()

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [34]:
# Count occurrences of each parental education level
data['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

### Handle Missing Values

In [35]:
# Print sum of missing values
data.isnull().sum()

#no missing values found

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

### Handle Duplicate Values

In [36]:
#Check for the duplicates
data.duplicated().sum()

#no duplicates found

np.int64(0)

### Filltering The Dataset

In [37]:
# Filter to include only students with 'math score' above the median
median_math_score = data['math score'].median()
filtered_df = data[data['math score'] > median_math_score]
print(filtered_df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
4      male        group C                some college      standard
5    female        group B          associate's degree      standard
..      ...            ...                         ...           ...
989  female        group D                some college  free/reduced
990    male        group E                 high school  free/reduced
995  female        group E             master's degree      standard
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
4                      none          76             78             75
5                      none          71             83             78
..                      ...         ...            ...            ...
989               completed          67             86             83
990               completed          86             81             75
995               completed          88             99             95
998               completed          68             78             77
999                    none          77             86             86

[493 rows x 8 columns]

In [38]:
# Count gender occurrences within each race/ethnicity group
data.groupby('race/ethnicity')['gender'].value_counts()

race/ethnicity  gender
group A         male       53
                female     36
group B         female    104
                male       86
group C         female    180
                male      139
group D         male      133
                female    129
group E         male       71
                female     69
Name: count, dtype: int64

In [42]:
# Count occurrences of each parental education level within each race/ethnicity group
data.groupby('race/ethnicity')['parental level of education'].value_counts()

race/ethnicity  parental level of education
group A         some high school               24
                high school                    18
                some college                   18
                associate's degree             14
                bachelor's degree              12
                master's degree                 3
group B         high school                    48
                associate's degree             41
                some high school               38
                some college                   37
                bachelor's degree              20
                master's degree                 6
group C         associate's degree             78
                some college                   69
                high school                    64
                some high school               49
                bachelor's degree              40
                master's degree                19
group D         some college                   67
                associate's degree             50
                some high school               50
                high school                    44
                bachelor's degree              28
                master's degree                23
group E         associate's degree             39
                some college                   35
                high school                    22
                bachelor's degree              18
                some high school               18
                master's degree                 8
Name: count, dtype: int64

In [43]:
# Count students with bad math scores below 50, grouped by test preparation course, sorted in descending order
bad_math =data[data['math score']<50]
bad_math.groupby('test preparation course')['math score'].count().sort_values(ascending=False)

test preparation course
none         107
completed     28
Name: math score, dtype: int64

### Dataset Feature Engineering

In [41]:
# Add a new column 'average score' as the mean of the three score columns
data['average score'] = data[['math score', 'reading score', 'writing score']].mean(axis=1)
print(data.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score  \
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

   average score
0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333